server:
  port: 9999
  address: 127.0.0.1
  servlet:
    context-path: /generator
spring:
  profiles:
    active: prod
  freemarker:
    template-loader-path=classpath: /templates
    cache: true
    charset: utf-8
    check-template-location: true



# swagger配置
swagger:
  # 是否启用swagger，默认：true
  enabled: true
  # 标题
  title: "Spring Boot 实现数据库文档生成"
  contact:
    # 维护人
    name: "xxr"
    email: "abc@qq.com"
    url: "https://www.baidu.com"
  # 版本
  version: "1.0"
  # 描述
  description: "API 描述"
  # swagger扫描的基础包，默认：全扫描
  base-package: "org.hackerandpainter.databasedocgenerator.controller"
  # 需要处理的基础URL规则，默认：/**
  base-path: /**
  # 需要排除的URL规则，默认：空
  #  exclude-path: ""
  license: "Apache License, Version 2.0"
  license-url: "https://www.apache.org/licenses/LICENSE-2.0.html"

